version: '3'
services:
  javier-rms:
    build:
      context: .
      dockerfile: Dockerfile-Javier
    image: javierdvops/rms-docker-img:v2
    container_name: rms-docker-container
  Johnathon:
    build:
      context: .
      dockerfile: Dockerfile-Johnathon
    image: mentalpains/rms-docker-img:latest
    container_name: rms-docker-container
    