apiVersion: v1
kind: Service
metadata:
  name: rms-service-johnathon
spec:
  selector:
    app: rms-docker-img-johnathon
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5050
  type: LoadBalancer